"""
Bulk Excel Report Generator for Credit Analysis
Generates a summary Excel sheet with multiple analysis records
"""
import xlsxwriter
from datetime import datetime
from typing import List, Dict
import tempfile

class BulkExcelReportGenerator:
    def __init__(self, language='es'):
        self.language = language
        
    def generate(self, data: List[Dict], output_path: str):
        workbook = xlsxwriter.Workbook(output_path)
        worksheet = workbook.add_worksheet('Analysis Results' if self.language == 'en' else 'Resultados de Análisis')
        
        # Formats
        formats = {
            'header': workbook.add_format({
                'bold': True,
                'bg_color': '#253746',
                'font_color': 'white',
                'border': 1,
                'align': 'center',
                'valign': 'vcenter'
            }),
            'cell': workbook.add_format({'border': 1, 'valign': 'vcenter'}),
            'num': workbook.add_format({'border': 1, 'num_format': '#,##0.00', 'valign': 'vcenter'}),
            'center': workbook.add_format({'border': 1, 'align': 'center', 'valign': 'vcenter'}),
            'title': workbook.add_format({
                'bold': True,
                'font_size': 14,
                'font_color': '#11303B',
                'align': 'left'
            }),
            'subtitle': workbook.add_format({
                'font_size': 10,
                'font_color': '#666666',
                'align': 'left'
            }),
            'footer': workbook.add_format({
                'font_size': 9,
                'italic': True,
                'align': 'center',
                'font_color': '#666666'
            })
        }
        
        # Add Branding Header
        logo_path = 'app/assets/logo.png' 
        # Note: xlsxwriter looks for file path relative to execution or absolute. 
        # Ensuring we check if it exists or use absolute path logic if needed, but 'app/assets/logo.png' assumes running from root.
        # Better to be safe with safe check or try/except logic implicitly by xlsxwriter (it warns if not found).
        
        try:
             worksheet.insert_image('A1', logo_path, {'x_scale': 0.4, 'y_scale': 0.4, 'x_offset': 5, 'y_offset': 5})
        except:
             pass # Use text branding if image fails
             
        # Move Title down because of Logo
        worksheet.write('A4', 'Reporte Consolidado de Créditos' if self.language == 'es' else 'Consolidated Credit Report', formats['title'])
        
        # Table Start Row
        start_row = 6
        
        # Headers
        headers = {
            'en': ['Sr No', 'ID', 'Company Name', 'Analysis Date', 'Credit Score', 'Category', 'Status', 'Requested Amount', 'Approved Amount'],
            'es': ['No.', 'ID', 'Nombre de Empresa', 'Fecha de Análisis', 'Puntaje', 'Categoría', 'Estado', 'Monto Solicitado', 'Monto Autorizado']
        }[self.language]
        
        for col, header in enumerate(headers):
            worksheet.write(start_row, col, header, formats['header'])
            width = 15 if col in [0, 1, 4, 5] else 25
            worksheet.set_column(col, col, width)
            
        # Data
        for i, item in enumerate(data, start=1):
            row = start_row + i
            worksheet.write(row, 0, i, formats['center'])
            worksheet.write(row, 1, str(item.get('id')).zfill(6), formats['center'])
            worksheet.write(row, 2, item.get('company_name'), formats['cell'])
            worksheet.write(row, 3, item.get('date'), formats['center'])
            worksheet.write(row, 4, item.get('credit_score'), formats['num'])
            worksheet.write(row, 5, item.get('category'), formats['center'])
            worksheet.write(row, 6, item.get('status'), formats['center'])
            worksheet.write(row, 7, item.get('requested_amount'), formats['num'])
            worksheet.write(row, 8, item.get('approved_amount'), formats['num'])
            
        # Footer
        footer_row = start_row + len(data) + 2
        footer_text = f"Generado por Moskalti FinAI Agent - {datetime.now().strftime('%d/%m/%Y')} | © {datetime.now().year} Moskalti Capital"
        if self.language != 'es':
            footer_text = f"Generated by Moskalti FinAI Agent - {datetime.now().strftime('%d/%m/%Y')} | © {datetime.now().year} Moskalti Capital"
            
        worksheet.merge_range(footer_row, 0, footer_row, len(headers)-1, footer_text, formats['footer'])
            
        workbook.close()
