"""
Reporting Infrastructure: Individual Financial Workbooks.
Produces multi-sheet Excel reports with detailed financial snapshots, 
ratios, and risk indicators for expert review.
"""
import xlsxwriter
from datetime import datetime
from typing import Dict, List

class ExcelReportGenerator:
    """
    Detailed workbook orchestrator.
    Handles the creation of complex multi-sheet financial disclosures (Info, BS, IS, Ratios, SWOT).
    """
    
    def __init__(self, language='es'):
        self.language = language
        
    def _add_footer(self, worksheet, row, col_span, formats):
        """Standardized Branding Footer."""
        footer_text = {
            'es': f"Generado por Moskalti FinAI Agent - {datetime.now().strftime('%d/%m/%Y')} | © {datetime.now().year} Moskalti Capital",
            'en': f"Generated by Moskalti FinAI Agent - {datetime.now().strftime('%d/%m/%Y')} | © {datetime.now().year} Moskalti Capital"
        }[self.language if self.language in ['es', 'en'] else 'es']
            
        worksheet.merge_range(row, 0, row, col_span, footer_text, formats['footer'])
        
    def generate(self, analysis_data: Dict, company_data: Dict, financial_statements: List[Dict], output_path: str):
        """
        Orchestrates the complete workbook assembly flow.
        Creates sheets: Info -> Loan -> Balance Sheet -> Income Statement -> Ratios -> SWOT -> Score -> Recommendation.
        """
        workbook = xlsxwriter.Workbook(output_path)
        formats = self._create_formats(workbook)
        
        # Dynamic Sheet Initialization
        self._create_company_info_sheet(workbook, company_data, formats)
        self._create_loan_details_sheet(workbook, analysis_data, formats)
        self._create_balance_sheet(workbook, financial_statements, formats)
        self._create_income_statement(workbook, financial_statements, formats)
        self._create_financial_ratios_sheet(workbook, analysis_data, formats)
        self._create_swot_sheet(workbook, analysis_data, formats)
        self._create_credit_score_sheet(workbook, analysis_data, formats)
        self._create_recommendation_sheet(workbook, analysis_data, formats)
        
        workbook.close()
    
    def _create_formats(self, workbook):
        """Initializes the institutional design system within Excel formats."""
        return {
            'header': workbook.add_format({
                'bold': True, 'font_size': 14, 'bg_color': '#253746', 'font_color': 'white', 
                'align': 'center', 'valign': 'vcenter', 'border': 1
            }),
            'subheader': workbook.add_format({
                'bold': True, 'font_size': 12, 'bg_color': '#425563', 'font_color': 'white', 
                'align': 'center', 'border': 1
            }),
            'label': workbook.add_format({'bold': True, 'align': 'left', 'border': 1}),
            'value': workbook.add_format({'align': 'right', 'border': 1, 'num_format': '#,##0.00'}),
            'percent': workbook.add_format({'align': 'right', 'border': 1, 'num_format': '0.00%'}),
            'currency': workbook.add_format({'align': 'right', 'border': 1, 'num_format': '$#,##0.00'}),
            'footer': workbook.add_format({
                'font_size': 9, 'italic': True, 'align': 'center', 'font_color': '#666666'
            })
        }
  
